<h1><?= $this->viewData[0] ?></h1>
<div class="section">
	<p><?= $this->viewData[1] ?></p>
	<img src="<?= $this->viewData[2] ?>" alt="action association" style="float: left; border: 0;" \>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eu odio eu velit tincidunt cursus quis sodales mauris. Vestibulum egestas ultrices auctor. Duis adipiscing <a href="index.html">click here &gt;&gt;</a></p>
</div>';
	