<! DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>Page d'authentification</title>
    </head>
<body><!-- action="./../Adminsite/Menu.phtml" -->
    <p>AUTHENTIFICATION</p>
    <form  method="post" action="index.php">
        
    <label>Login :</label><input class="post" id="login" type="text" name="login"  required="required" value="" autocomplete="off" /> <br/>
    <label>Mot de passe :</label><input  class="post" id="pwd" type="password" name="pwd" required="required" value="" autocomplete="off" /> <br/>
<input type="submit" name="action" value="connection"/>
</form>
</body>
</html>


