<h1>Ajouter un nouveau rôle</h1>
<form id="form1" method="post">
	<table><tr><td>Nom du rôle : </td>
			<td>
				<input type="text" id="nomRole" name="nomRole" value="<?php echo $this->viewData['Roles']->getNomRole();?>"/>
				<span id="erreur"><?php echo $this->viewData['Roles']->ValidationMessage("nomRole"); ?>
				</span>
			</td>
		</tr>
		<tr><td colspan='2'><input type="submit" value="Ajouter" /></td></tr>
	</table>
</form>