<h1>Modifier un rôle</h1>

<form id="form1" method="post">
	<table>
		<tr><td>Id : </td>
			<td><input type="text" id="idRole" name="idRole" readonly="true" value="<?php echo $this->viewData['Role']->getId();?>"/>
			</td>
		</tr>
		<tr><td>Nom du Role : </td>
			<td><input type="text" id="nomRole" name="nomRole" value="<?php echo $this->viewData['Role']->getNomRole();?>"/>
			<span id="erreur"><?php echo $this->viewData['Role']->ValidationMessage("nomRole");?></span>
			</td>
		</tr>
		
		
		<tr><td colspan='2'><input type="submit" 
		value= "  Modifier  " /></td></tr>
	</table>
</form>